# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 08:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('block', 'firstName')},
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.AddField(
            model_name='driver',
            name='fullName',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
