# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180510_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tba',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
