# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180510_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='tba',
            name='city',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='tba',
            name='sortZone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='tba',
            name='zipCode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tba',
            name='address',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='tba',
            name='link',
            field=models.CharField(max_length=50),
        ),
    ]
